# Generated by Django 4.2 on 2023-04-25 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_rating_movie_alter_rating_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
    ]
