# Generated by Django 4.2 on 2023-04-29 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_rating_rating"),
    ]

    operations = []
